attacks = [
    {
        "types": ["Flame"],
        "name": "Firespin",
        "energy": ["Flame"] * 3,
        "description": "",
        "damage": 30,
    },
    {
        "types": ["Flame"],
        "name": "Flame punch",
        "energy": ["Flame"] * 3,
        "description": "",
        "damage": 40,
    },
    {
        "types": ["Flame"],
        "name": "Wildfire",
        "energy": ["Flame"] * 5,
        "description": "This attack does 20 damage to this card.",
        "damage": 140,
    },
    {
        "types": ["Flame"],
        "name": "Steam wall",
        "energy": ["Flame"] * 2 + ["Wave"] * 2,
        "description": "Halve the next damage done to this card.",
        "damage": "",
    },
    {
        "types": ["Flame"],
        "name": "lava pour",
        "energy": ["Flame"] * 4,
        "description": "your opponent is burned",
        "damage": 50,
    },
    {
        "types": ["Flame", "Lightning"],
        "name": "Hot bolt",
        "energy": ["Flame"] * 2 + ["Lightning"] * 3,
        "description": "",
        "damage": 140,
    },
    {
        "types": ["Flame"],
        "name": "Charcoal",
        "energy": ["Flame"] * 3 + ["stone"],
        "description": "",
        "damage": 120,
    },
    {
        "types": ["Flame"],
        "name": "Grassfire",
        "energy": ["Flame"] * 1 + ["Leaf"] * 4,
        "description": "+ 100 if your opponent is leaf type",
        "damage": 100,
    },
    {
        "types": ["Lightning"],
        "name": "Thunder slam",
        "energy": ["Lightning"] * 3,
        "description": "",
        "damage": 50,
    },
    {
        "types": ["Lightning"],
        "name": "Lightning rod",
        "energy": ["Lightning"] * 5,
        "description": "Lightning moves do x2 their normal damage",
        "damage": 50,
    },
    {
        "types": ["Wave", "Lightning"],
        "name": "Storm",
        "energy": ["Lightning"] * 2 + ["Wave"] * 2,
        "description": "20 damage each turn to all cards",
        "damage": 20,
    },
    {
        "types": ["Leaf"],
        "name": "grass blade",
        "energy": ["leaf"] * 3,
        "description": "",
        "damage": 90,
    },
    {
        "types": ["Leaf", "Wave"],
        "name": "Seaweed",
        "energy": ["Wave"] * 3 + ["Leaf"],
        "description": "",
        "damage": 120,
    },
    {
        "types": ["Wave"],
        "name": "Wave",
        "energy": ["Wave"] * 3,
        "description": "",
        "damage": 90,
    },
    {
        "types": ["Spell"],
        "name": "Energy Sheild",
        "energy": ["Spell"] * 3,
        "description": "Halve the next damage done to this card",
        "damage": "",
     },]

for i, attack in enumerate(attacks):
    attack["id"] = i
