attacks = [
    {
        "types": ["Flame"],
        "name": "Firespin",
        "description": "",
        "damage": 30,
        "energy": 2,
    },
    {
        "types": ["Flame"],
        "name": "Flame punch",
        "description": "",
        "damage": 50,
        "energy": 3,
    },

    {
        "types": ["Flame"],
        "name": "Wildfire",
        "description": "This attack does 20 damage to this card.",
        "damage": 70,
        "energy": 4,
    },
    {
        "types": ["Flame", "Wave"],
        "name": "Steam wall",
        "description": "Halve the next damage done to this card.",
        "damage": "",
        "energy": 4,
    },
    {
        "types": ["Flame"],
        "name": "Lava pour",
        "description": "This attack does 20 damage your next turn.",
        "damage": 50,
        "energy": 6,
    },
    {
        "types": ["Flame", "Lightning"],
        "name": "Hot bolt",
        "description": "",
        "damage": 20,
        "energy": 1,
    },
    {
        "types": ["Flame", "Earth"],
        "name": "Charcoal",
        "description": "",
        "damage": 40,
        "energy": 3,
    },
    {
        "types": ["Flame"],
        "name": "Grassfire",
        "description": "+70 damage if your opponent is leaf type",
        "damage": 50,
        "energy": 5,
    },
    {
        "types": ["Lightning"],
        "name": "Thunder slam",
        "description": "",
        "damage": 50,
        "energy": 3,
    },
    {
        "types": ["Lightning"],
        "name": "Lightning rod",
        "description": "Your next turn lightning types' moves do \n x2 their normal damage",
        "damage": 50,
        "energy": 5,
    },
    {
        "types": ["Wave", "Lightning"],
        "name": "Storm",
        "description": "Do 20 damage next turn to all cards",
        "damage": 20,
        "energy": 5,
    },
    {
        "types": ["Leaf", "Wave"],
        "name": "Seaweed",
        "description": "",
        "damage": 120,
        "energy": 5,
    },
    {
        "types": ["Leaf"],
        "name": "Petal Punch",
        "description": "",
        "damage": 50,
        "energy": 3,
    },
    {
        "types": ["Spell"],
        "name": "Energy Shield",
        "description": "Halve the next damage done to this card",
        "damage": "",
        "energy": 5,
    },
    {
        "types": ["Leaf"],
        "name": "Growth",
        "description": "Draw a card.",
        "damage": "",
        "energy": 1,
    },
    {
        "types": ["Leaf"],
        "name": "Grass Spin",
        "description": "",
        "damage": 50,
        "energy": 3,
    },
    {
        "types": ["Leaf"],
        "name": "Leaf Smack",
        "description": "",
        "damage": 70,
        "energy": 5,
    },
    {
        "types": ["Ice"],
        "name": "Snowfall",
        "description": "",
        "damage": 60,
        "energy": 4,
    },
    {
        "types": ["Earth"],
        "name": "Boulder crash",
        "description": "This attack may do 60 more damage.\n If it does, this card does 50 damage \n to itself.",
        "damage": "80",
        "energy": 6,
    },
    {
        "types": ["Earth"],
        "name": "Stand Very Still",
        "description": "Add two attack tokens",
        "damage": "40",
        "energy": 1,
    },
    {
        "types": ["Ice"],
        "name": "Ice dash",
        "description": "Draw 2 cards. This attack does 20 damage \n for each card now in your hand.",
        "damage": "0+",
        "energy": 5,
    },
    {
        "types": ["Leaf", "Poison"],
        "name": "Poison Ivy",
        "description": "your next turn, poison types' attacks do \n +80 damage ",
        "damage": "40",
        "energy": 3,
    },
    {
        "types": ["Fire",],
        "name": "Rainbow Wildfire",
        "description": "",
        "damage": "70",
        "energy": 3,
    },
    {
        "types": ["Wave", "Lightning"],
        "name": "Rainbow Storm",
        "description": "40 damage next turn to all cards",
        "damage": 40,
        "energy": 5,
    },
    {
        "types": ["Flame", "Air"],
        "name": "Firenado",
        "description": "",
        "damage": 60,
        "energy": 3,
    },
    {
        "types": ["Leaf", "Metal"],
        "name": "Iron Leaf",
        "description": "",
        "damage": 40,
        "energy": 2,
    },
    {
        "types": ["Lightning", "Shadow"],
        "name": "Shadow Storm",
        "description": "attatch 2 attack tokens to any card/s.",
        "damage": 40,
        "energy": 4,
    },
    {
        "types": ["Wave", "Spell"],
        "name": "Enchanting Water",
        "description": "Heal 70 damage in any way.",
        "damage": 0,
        "energy": 4,
    },
     {
        "types": ["Any"],
        "name": "Hidden Dagger",
        "description": "Damage cannot be altered in any way.",
        "damage": 20,
        "energy": 1,
    },
    ]

for i, attack in enumerate(attacks):
    attack["id"] = i
